INFO:root:Informational message
ERROR:root:An error has happened!
ERROR:ex:Error!
Traceback (most recent call last):
  File "logger.py", line 7, in <module>
    raise RuntimeError
RuntimeError
